# Usa una imagen base de Node
FROM node:20

# Crea un directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el archivo package.json y package-lock.json desde la carpeta correcta
COPY libreria/package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de la aplicación
COPY libreria ./ 

# Expone el puerto de la aplicación
EXPOSE 3003

# Define el comando para iniciar la aplicación
CMD ["npm", "start"]
