FROM postgres:17

RUN apt-get update && \
    apt-get install -y postgresql-contrib && \
    apt-get install -y postgresql-17-pgaudit && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./postgresql.configs/postgresql.conf /etc/postgresql/postgresql.conf

RUN echo "include '/etc/postgresql/postgresql.conf'" >> /usr/share/postgresql/postgresql.conf.sample

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]